# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Generate Graphs
gem 'rmagick', '~> 5.3'
gem 'gruff'
gem 'stop_watch'
gem 'minitest'
gem 'fileutils'
gem 'benchmark-ips'
gem 'benchmark-memory'
